In [2]:
import numpy as np
import scipy.linalg as linalg

#1
<br>
After the coordinates of the circle are subtitude in the given equations, these are the result:
<br>
$$ -2a + 7b + c = -53 $$
$$ -4a + 5b + c = -41 $$
$$ 4a - 3b + c = -25 $$
<br>

So, we can define A and b as:
<br>
$$A = \begin{bmatrix} -2 & 7 & 1 \\ -4 & 5 & 1 \\ 4 & -3 & 1 \end{bmatrix}$$ 
and $$b = \begin{bmatrix} -53 \\  -41 \\ -25 \\ \end{bmatrix}$$

In [3]:
# create array A and b
A = np.array([[-2,7,1],
             [-4,5,1], 
             [4,-3,1]])
b = np.array([[-53,-41,-25]]).T
print("--------------- A --------------- \n", A)
print("--------------- b --------------- \n", b)

# create x as the result 
x = linalg.solve(A, b)
print("--------------- result --------------- \n", x)

#TODO check if the result is correct

--------------- A --------------- 
 [[-2  7  1]
 [-4  5  1]
 [ 4 -3  1]]
--------------- b --------------- 
 [[-53]
 [-41]
 [-25]]
--------------- result --------------- 
 [[ -2.]
 [ -4.]
 [-29.]]


As the result, a , b, and c are:
<br>
$$a = -2$$

$$b = -4$$

$$c = -29$$
***

#2
<br>
According to the conditions E1, E2, E3, and E4 can be written as:
$$E_1 = BA^{-1}$$
$$E_2 = AB^{-1}$$
$$E_3 = CA^{-1}$$
$$E_4 = AC^{-1}$$

In [4]:
A = np.array([[3, 4, 1],
             [2, -7, -1],
             [8, 1, 5]])

B = np.array([[8, 1, 5],
             [2, -7, -1],
             [3, 4, 1]])

C = np.array([[3, 4, 1],
             [2, -7, -1],
             [2, -7, 3]])

# calculate inverse
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
C_inv = np.linalg.inv(C)

# multiplying matrix

E_1 = np.matmul(B, A_inv)
E = np.rint(E_1)
print("--------------- E1 ---------------\n", E)
E_2 = np.matmul(A, B_inv)
E = np.rint(E_2)
print("--------------- E2 ---------------\n", E)
E_3 = np.matmul(C, A_inv)
E = np.rint(E_3)
print("--------------- E3 ---------------\n", E)
E_4 = np.matmul(A, C_inv)
E = np.rint(E_4)
print("--------------- E4 ---------------\n", E)

#TODO check if the result is correct

--------------- E1 ---------------
 [[ 0.  0.  1.]
 [-0.  1.  0.]
 [ 1. -0.  0.]]
--------------- E2 ---------------
 [[ 0. -0.  1.]
 [ 0.  1. -0.]
 [ 1.  0.  0.]]
--------------- E3 ---------------
 [[ 1. -0.  0.]
 [-0.  1.  0.]
 [-2.  0.  1.]]
--------------- E4 ---------------
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 2.  0.  1.]]


As a result, the elementary matrices are:
$$E_1 = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{bmatrix}$$
$$E_2 = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{bmatrix}$$
$$E_3 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 2 & 0 & 1 \end{bmatrix}$$
$$E_4 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 2 & 0 & 1 \end{bmatrix}$$

***

#3
<br>
For avoiding the pivoting issue in numpy, the doolittle algorithm is used to calculate the matrix L and U. The algorithm can be written as:

In [5]:
def LUdecomp(a):
    n = len(a)
    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k]/a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam*a[k, k+1:n]
                a[i, k] = lam
    return a


Ref: https://stackoverflow.com/questions/48370944/lu-decomp-without-pivoting-in-python

In [6]:
# for (a)

A = np.array([[3,1],
             [9,5]])

A_doo = LUdecomp(A)
print("A_doo:\n", A_doo)

L_doo = np.array([[1, 0],
                 [A_doo[1, 0], 1]])
U_doo = np.array([[A_doo[0, 0],
                 A_doo[0, 1]], 
                 [0, A_doo[1, 1]]])
print("L_doo:\n", L_doo)
print("U_doo:\n", U_doo)

# check if L and U are correct
ALU_doo = np.dot(L_doo, U_doo)
print("ALU: \n", ALU_doo)


A_doo:
 [[3 1]
 [3 2]]
L_doo:
 [[1 0]
 [3 1]]
U_doo:
 [[3 1]
 [0 2]]
ALU: 
 [[3 1]
 [9 5]]


The answers for (a) are:
$$L = \begin{bmatrix} 1 & 0 \\ 3 & 1 \end{bmatrix}$$
$$U = \begin{bmatrix} 3 & 1 \\ 0 & 2 \end{bmatrix}$$

In [7]:
# for (b)

B = np.array([[1,1,1],
             [3,5,6],
              [-2,2,7]])

B_doo = LUdecomp(B)
print("B_doo:\n", B_doo)

L_doo = np.array([[1, 0, 0],
                 [B_doo[1, 0], 1, 0],
                 [B_doo[2, 0], B_doo[2, 1], 1]])
print("L:\n", L_doo)

U_doo = np.array([[B_doo[0, 0], B_doo[0, 1], B_doo[0, 2]],
                 [0, B_doo[1, 1], B_doo[1, 2]], 
                 [0, 0, B_doo[2, 2]]])
print("U:\n", U_doo)


B_doo:
 [[ 1  1  1]
 [ 3  2  3]
 [-2  2  3]]
L:
 [[ 1  0  0]
 [ 3  1  0]
 [-2  2  1]]
U:
 [[1 1 1]
 [0 2 3]
 [0 0 3]]


The answers for (b) are: 

$$L = \begin{bmatrix} 1 & 0 & 0 \\ 3 & 1 & 0 \\ -2 & 2 & 1 \end{bmatrix}$$
$$U = \begin{bmatrix} 1 & 1 & 1 \\ 0 & 2 & 3 \\ 0 & 0 & 3 \end{bmatrix}$$


***

#5
<br>
Compare the computational time for solving a system of 10x10, 50x50, 100x100, and 500x500 between 2 different methods: gauss elimination and matrix inversion. The percentage difference is calculated by the formula:
$$\% t_{diff} = 100 \times \dfrac {t_{inv} - t_{gauss}} {t_{gauss}}$$

In [8]:
import time
t_sum = 0

for _ in range(1000):
    A = np.random.randn(100,100)
    b = np.random.randn(100,)
    t1 = time.process_time()
    x = np.dot(np.linalg.inv(A), b)
    t2 = time.process_time()
    t_sum += t2 - t1
t_avg = t_sum/1000
t_avg_ms = t_avg * 1000
print(f"avg time: {t_avg_ms:.3f} ms")

avg time: 0.766 ms
