In [63]:
import numpy as np
import scipy.linalg as linalg

#5
</br>
Generate 5x5 matrix and create some random number from student id: 6210550614, so the number used will be 614.

In [64]:
id_no = 614
np.random.seed(seed=id_no)
n = 5

def random_matrix(n):
    return np.round(3*np.random.rand(n,n)-0.5)

A = random_matrix(n)
print(A)

[[ 2.  1. -0.  0.  2.]
 [ 1.  1.  0.  1.  2.]
 [-0.  2. -0.  2.  2.]
 [ 1. -0.  1.  1.  2.]
 [ 2.  1.  2.  0.  2.]]


In [65]:
detA = np.linalg.det(A)
print(detA)


0.0


Find the determinant of A using cofactors.
<br>
ref: https://www.geeksforgeeks.org/determinant-of-a-matrix/

In [66]:
# get cofactor of matrix m
def get_cofactor(m, i, j):
    
    return np.delete(np.delete(m, i, axis=0), j, axis=1)

# calculate determinant of the matrix
def calculate_det(mat):

    if(len(mat) == 2):
        value = mat[0][0] * mat[1][1] - mat[1][0] * mat[0][1]
        return value

    Sum = 0

    # create loop for each column in the matrix
    for current_column in range(len(mat)):

        # calculating the sign according to the cofactor
        sign = (-1) ** (current_column)

        # calculate sub det
        sub_det = calculate_det(get_cofactor(mat, 0, current_column))

        Sum += (sign * mat[0][current_column] * sub_det)

    # returning the final Sum
    return Sum

find_det = calculate_det(A)
print(find_det)

# check is the answer is correct

if (find_det == detA):
    print("The determinant is equal")
else:
    print("The determinant is not equal")


0.0
The determinant is equal


Next, calculate and compare the run time for each algorithm

In [67]:
import time


In [74]:
# 5 x 5 matrix
print("5 x 5")

# create a random matrix of dimension 5 x 5
A = random_matrix(5)

t1_np = time.process_time()
npdet = np.linalg.det(A)
t2_np = time.process_time()

t_np = (t2_np - t1_np) * 1000
print(f"Computational time for numpy is {t_np:.3f} ms")

t1_co = time.process_time()
codet = calculate_det(A)
t2_co = time.process_time()

t_co = (t2_co - t1_co) * 1000
print(f"Computational time for cofactoris {t_co:.3f} ms")

t_diff = np.abs(100 * (t_np - t_co) / t_co)

print(f"Percent difference: {t_diff:.3f} %")

if(npdet == codet):
    print(f"The determinant is {npdet}")

else:
    print(f"The determinant for numpy is {npdet}")
    print(f"The determinant for cofactor is {codet}")


5 x 5
Computational time for numpy is 0.096 ms
Computational time for cofactoris 5.098 ms
Percent difference: 98.108 %
The determinant is 0.0


In [69]:
# 6 x 6 matrix
print("6 x 6")

# create a random matrix of dimension 6 x 6
A = random_matrix(6)

t1_np = time.process_time()
npdet = np.linalg.det(A)
t2_np = time.process_time()

t_np = (t2_np - t1_np) * 1000
print(f"Computational time for numpy is {t_np:.3f} ms")

t1_co = time.process_time()
codet = calculate_det(A)
t2_co = time.process_time()

t_co = (t2_co - t1_co) * 1000
print(f"Computational time for cofactoris {t_co:.3f} ms")

t_diff = np.abs(100 * (t_np - t_co) / t_co)

print(f"Percent difference: {t_diff:.3f} %")

if(npdet == codet):
    print(f"The determinant is {npdet}")

else:
    print(f"The determinant for numpy is {npdet}")
    print(f"The determinant for cofactor is {codet}")


6 x 6
Computational time for numpy is 0.089 ms
Computational time for cofactoris 21.786 ms
Percent difference: 99.592 %
The determinant for numpy is -27.999999999999986
The determinant for cofactor is -28.0


In [70]:
# 7 x 7 matrix
print("7 x 7")

# create a random matrix of dimension 7 x 7
A = random_matrix(7)

t1_np = time.process_time()
npdet = np.linalg.det(A)
t2_np = time.process_time()

t_np = (t2_np - t1_np) * 1000
print(f"Computational time for numpy is {t_np:.3f} ms")

t1_co = time.process_time()
codet = calculate_det(A)
t2_co = time.process_time()

t_co = (t2_co - t1_co) * 1000
print(f"Computational time for cofactoris {t_co:.3f} ms")

t_diff = np.abs(100 * (t_np - t_co) / t_co)

print(f"Percent difference: {t_diff:.3f} %")

if(npdet == codet):
    print(f"The determinant is {npdet}")

else:
    print(f"The determinant for numpy is {npdet}")
    print(f"The determinant for cofactor is {codet}")


7 x 7
Computational time for numpy is 0.129 ms
Computational time for cofactoris 55.667 ms
Percent difference: 99.769 %
The determinant for numpy is 59.999999999999986
The determinant for cofactor is 60.0


In [75]:
# 8 x 8 matrix
print("8 x 8")

# create a random matrix of dimension 8 x 8
A = random_matrix(8)

t1_np = time.process_time()
npdet = np.linalg.det(A)
t2_np = time.process_time()

t_np = (t2_np - t1_np) * 1000
print(f"Computational time for numpy is {t_np:.3f} ms")

t1_co = time.process_time()
codet = calculate_det(A)
t2_co = time.process_time()

t_co = (t2_co - t1_co) * 1000
print(f"Computational time for cofactoris {t_co:.3f} ms")

t_diff = np.abs(100 * (t_np - t_co) / t_co)

print(f"Percent difference: {t_diff:.3f} %")

if(npdet == codet):
    print(f"The determinant is {npdet}")

else:
    print(f"The determinant for numpy is {npdet}")
    print(f"The determinant for cofactor is {codet}")


8 x 8
Computational time for numpy is 0.140 ms
Computational time for cofactoris 437.268 ms
Percent difference: 99.968 %
The determinant for numpy is 65.99999999999997
The determinant for cofactor is 66.0


In [76]:
# 9 x 9 matrix
print("9 x 9")

# create a random matrix of dimension 9 x 9
A = random_matrix(9)

t1_np = time.process_time()
npdet = np.linalg.det(A)
t2_np = time.process_time()

t_np = (t2_np - t1_np) * 1000
print(f"Computational time for numpy is {t_np:.3f} ms")

t1_co = time.process_time()
codet = calculate_det(A)
t2_co = time.process_time()

t_co = (t2_co - t1_co) * 1000
print(f"Computational time for cofactoris {t_co:.3f} ms")

t_diff = np.abs(100 * (t_np - t_co) / t_co)

print(f"Percent difference: {t_diff:.3f} %")

if(npdet == codet):
    print(f"The determinant is {npdet}")

else:
    print(f"The determinant for numpy is {npdet}")
    print(f"The determinant for cofactor is {codet}")


9 x 9
Computational time for numpy is 0.098 ms
Computational time for cofactoris 3177.178 ms
Percent difference: 99.997 %
The determinant for numpy is -21.00000000000001
The determinant for cofactor is -21.0


In [77]:
# 10 x 10 matrix
print("10 x 10")

# create a random matrix of dimension 10 x 10
A = random_matrix(10)

t1_np = time.process_time()
npdet = np.linalg.det(A)
t2_np = time.process_time()

t_np = (t2_np - t1_np) * 1000
print(f"Computational time for numpy is {t_np:.3f} ms")

t1_co = time.process_time()
codet = calculate_det(A)
t2_co = time.process_time()

t_co = (t2_co - t1_co) * 1000
print(f"Computational time for cofactoris {t_co:.3f} ms")

t_diff = np.abs(100 * (t_np - t_co) / t_co)

print(f"Percent difference: {t_diff:.3f} %")

if(npdet == codet):
    print(f"The determinant is {npdet}")

else:
    print(f"The determinant for numpy is {npdet}")
    print(f"The determinant for cofactor is {codet}")


10 x 10
Computational time for numpy is 0.108 ms
Computational time for cofactoris 29708.580 ms
Percent difference: 100.000 %
The determinant for numpy is 161.99999999999994
The determinant for cofactor is 162.0
