In [9]:
import numpy as np
import scipy.linalg as linalg

#5
</br>
Generate 5x5 matrix and create some random number from student id: 6210550614, so the number used will be 614.

In [10]:
id_no = 614
np.random.seed(seed=id_no)
n = 5

def random_matrix(n):
    return np.round(3*np.random.rand(n,n)-0.5)

A = random_matrix(n)
print(A)

[[ 2.  1. -0.  0.  2.]
 [ 1.  1.  0.  1.  2.]
 [-0.  2. -0.  2.  2.]
 [ 1. -0.  1.  1.  2.]
 [ 2.  1.  2.  0.  2.]]


In [11]:
detA = np.linalg.det(A)
print(detA)


0.0


Find the determinant of A using cofactors.
<br>
ref: https://www.geeksforgeeks.org/determinant-of-a-matrix/

In [13]:
# get cofactor of matrix m
def getcofactor(m, i, j):
    
    return np.delete(np.delete(m, i, axis=0), j, axis=1)

# calculate determinant of the matrix
def determinantOfMatrix(mat):

    if(len(mat) == 2):
        value = mat[0][0] * mat[1][1] - mat[1][0] * mat[0][1]
        return value

    Sum = 0

    # create loop for each column in the matrix
    for current_column in range(len(mat)):

        # calculating the sign according to the cofactor
        sign = (-1) ** (current_column)

        # calculate sub det
        sub_det = determinantOfMatrix(getcofactor(mat, 0, current_column))

        Sum += (sign * mat[0][current_column] * sub_det)

    # returning the final Sum
    return Sum

find_det = determinantOfMatrix(A)
print(find_det)

# check is the answer is correct

if (find_det == detA):
    print("The determinant is equal")
else:
    print("The determinant is not equal")


0.0
The determinant is equal


Next, calculate and compare the run time for each algorithm