In [1]:
import numpy as np
import scipy.linalg as linalg

#5
</br>
Generate 5x5 matrix and create some random number from student id: 6210550614, so the number used will be 614.

In [2]:
id_no = 614
np.random.seed(seed=id_no)
A = np.round(3*np.random.rand(5,5)-0.5)
print(A)

[[ 2.  1. -0.  0.  2.]
 [ 1.  1.  0.  1.  2.]
 [-0.  2. -0.  2.  2.]
 [ 1. -0.  1.  1.  2.]
 [ 2.  1.  2.  0.  2.]]


In [3]:
detA = np.linalg.det(A)
print(detA)

0.0
