In [145]:
import numpy as np
import scipy.linalg as linalg

#5
</br>
Generate 5x5 matrix and create some random number from student id: 6210550614, so the number used will be 614.

In [146]:
id_no = 614
np.random.seed(seed=id_no)
n=5
A = np.round(3*np.random.rand(n,n)-0.5)
print(A)

[[ 2.  1. -0.  0.  2.]
 [ 1.  1.  0.  1.  2.]
 [-0.  2. -0.  2.  2.]
 [ 1. -0.  1.  1.  2.]
 [ 2.  1.  2.  0.  2.]]


In [147]:
detA = np.linalg.det(A)
print(detA)


0.0


Find the determinant of A using cofactors.
<br>
ref: https://www.geeksforgeeks.org/determinant-of-a-matrix/

In [150]:
# python program to find
# determinant of matrix.

# defining a function to get the
# minor matrix after excluding
# i-th row and j-th column.


def getcofactor(m, i, j):
    
    return np.delete(np.delete(m, i, axis=0), j, axis=1)

# defining the function to
# calculate determinant value
# of given matrix a.


def determinantOfMatrix(mat):

    # if given matrix is of order
    # 2*2 then simply return det
    # value by cross multiplying
    # elements of matrix.
    if(len(mat) == 2):
        value = mat[0][0] * mat[1][1] - mat[1][0] * mat[0][1]
        return value

    # initialize Sum to zero
    Sum = 0

    # loop to traverse each column
    # of matrix a.
    for current_column in range(len(mat)):

        # calculating the sign corresponding
        # to co-factor of that sub matrix.
        sign = (-1) ** (current_column)

        # calling the function recursily to
        # get determinant value of
        # sub matrix obtained.
        sub_det = determinantOfMatrix(getcofactor(mat, 0, current_column))

        # adding the calculated determinant
        # value of particular column
        # matrix to total Sum.
        Sum += (sign * mat[0][current_column] * sub_det)

    # returning the final Sum
    return Sum

find_det = determinantOfMatrix(A)
print(find_det)


0.0
