In [ ]:
import numpy as np
import scipy.linalg as linalg

#1
<br>
After the coordinates of the circle are subtitude in the given equations, these are the result:
<br>
(1) -2a + 7b + c = -53
<br>
(2) -4a + 5b + c = -41
<br>
(3) 4a - 3b + c = -25
<br>

So, we can define A and b as:
<br>
$$A = \begin{bmatrix} -2 & 7 & 1 \\ -4 & 5 & 1 \\ 4 & -3 & 1 \end{bmatrix}$$ 
and $$b = \begin{bmatrix} -53 \\  -41 \\ -25 \\ \end{bmatrix}$$

In [2]:
# create array A and b
A = np.array([[-2,7,1],
             [-4,5,1], 
             [4,-3,1]])
b = np.array([[-53,-41,-25]]).T
print("--------------- A --------------- \n", A)
print("--------------- b --------------- \n", b)

# create x as the result 
x = linalg.solve(A, b)
print("--------------- result --------------- \n", x)

#TODO check if the result is correct

--------------- A --------------- 
 [[-2  7  1]
 [-4  5  1]
 [ 4 -3  1]]
--------------- b --------------- 
 [[-53]
 [-41]
 [-25]]
--------------- result --------------- 
 [[ -2.]
 [ -4.]
 [-29.]]


As the result, a , b, and c are:
<br>
$$a = -2$$

$$b = -4$$

$$c = -29$$
***

#2
<br>
According to the conditions E1, E2, E3, and E4 can be written as:
$$E_1 = BA^{-1}$$
$$E_2 = AB^{-1}$$
$$E_3 = CA^{-1}$$
$$E_4 = AC^{-1}$$

In [13]:
A = np.array([[3, 4, 1],
             [2, -7, -1],
             [8, 1, 5]])

B = np.array([[8, 1, 5],
             [2, -7, -1],
             [3, 4, 1]])

C = np.array([[3, 4, 1],
             [2, -7, -1],
             [2, -7, 3]])

# calculate inverse
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
C_inv = np.linalg.inv(C)

# multiplying matrix

E_1 = np.matmul(B, A_inv)
E = np.rint(E_1)
print("--------------- E1 ---------------\n", E)
E_2 = np.matmul(A, B_inv)
E = np.rint(E_2)
print("--------------- E2 ---------------\n", E)
E_3 = np.matmul(C, A_inv)
E = np.rint(E_3)
print("--------------- E3 ---------------\n", E)
E_4 = np.matmul(A, C_inv)
E = np.rint(E_4)
print("--------------- E4 ---------------\n", E)

#TODO check if the result is correct

--------------- E1 ---------------
 [[ 0.  0.  1.]
 [-0.  1.  0.]
 [ 1.  0.  0.]]
--------------- E2 ---------------
 [[ 0.  0.  1.]
 [ 0.  1. -0.]
 [ 1.  0.  0.]]
--------------- E3 ---------------
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [-2.  0.  1.]]
--------------- E4 ---------------
 [[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 2.  0.  1.]]


As a result, the elementary matrices are:
$$E_1 = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{bmatrix}$$
$$E_2 = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{bmatrix}$$
$$E_3 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 2 & 0 & 1 \end{bmatrix}$$
$$E_4 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 2 & 0 & 1 \end{bmatrix}$$

***