#1
<br>
After the coordinates of the circle are subtitude in the given equations, these are the result:
<br>
(1) -2a + 7b + c = -53
<br>
(2) -4a + 5b + c = -41
<br>
(3) 4a - 3b + c = -25
<br>

So, we can define A and b as:
<br>
$$A = \begin{bmatrix} -2 & 7 & 1 \\ -4 & 5 & 1 \\ 4 & -3 & 1 \end{bmatrix}$$ 
and $$b = \begin{bmatrix} -53 \\  -41 \\ -25 \\ \end{bmatrix}$$

In [2]:
# create array A and b
A = np.array([[-2,7,1],
             [-4,5,1], 
             [4,-3,1]])
b = np.array([[-53,-41,-25]]).T
print("--------------- A --------------- \n", A)
print("--------------- b --------------- \n", b)

# create x as the result 
x = linalg.solve(A, b)
print("--------------- result --------------- \n", x)

--------------- A --------------- 
 [[-2  7  1]
 [-4  5  1]
 [ 4 -3  1]]
--------------- b --------------- 
 [[-53]
 [-41]
 [-25]]
--------------- result --------------- 
 [[ -2.]
 [ -4.]
 [-29.]]


As the result, a , b, and c are:
<br>
a = -2
<br>
b = -4
<br>
c = -29
***

#2
<br>
According to the conditions E1, E2, E3, and E4 can be written as:
$$E_1 = BA^{-1}$$
$$E_2 = AB^{-1}$$
$$E_3 = CA^{-1}$$
$$E_4 = AC^{-1}$$

In [9]:
A = np.array([[3, 4, 1],
             [2, -7, -1],
             [8, 1, 5]])

B = np.array([[8, 1, 5],
             [2, -7, -1],
             [3, 4, 1]])

C = np.array([[3, 4, 1],
             [2, -7, -1],
             [2, -7, 3]])

# calculate inverse
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
C_inv = np.linalg.inv(C)

# print("--------------- A --------------- \n", A)
# print("--------------- B --------------- \n", B)
# print("--------------- C --------------- \n", C)

# print("--------------- A inverse --------------- \n", A_inv)
# print("--------------- B inverse --------------- \n", B_inv)
# print("--------------- C inverse --------------- \n", C_inv)

E_1 = np.matmul(B, A_inv)
print(E_1)
E_2 = np.matmul(A, B_inv)
E_3 = np.matmul(C, A_inv)
E_4 = np.matmul(A, C_inv)

[[ 0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [-1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00]]
