#1
After the coordinates of the circle are subtitude in the given equations, these are the result:

(1) -2a + 7b + c = -53
(2) -4a + 5b + c = -41
(3) 4a - 3b + c = -25


In [2]:
import scipy.linalg as linalg
import numpy as np

# use lower-upper triangles to describe A

#TODO create array A and b
A = np.array([[-2,7,1],
             [-4,5,1], 
             [4,-3,1]])
b = np.array([[-53,-41,-25]]).T
print("--------------- A --------------- \n", A)
print("--------------- b --------------- \n", b)

x = linalg.solve(A, b)
print("--------------- result --------------- \n", x)


--------------- A --------------- 
 [[-2  7  1]
 [-4  5  1]
 [ 4 -3  1]]
--------------- b --------------- 
 [[-53]
 [-41]
 [-25]]
--------------- result --------------- 
 [[ -2.]
 [ -4.]
 [-29.]]


As the result, a , b, and c are:

a = -2
b = -4
c = -29